USE `orcamentos_v2`;
ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS nome_simplex VARCHAR(255) NULL AFTER nome,
  ADD COLUMN IF NOT EXISTS web_page VARCHAR(255) NULL AFTER email,
  ADD COLUMN IF NOT EXISTS telemovel VARCHAR(64) NULL AFTER telefone,
  ADD COLUMN IF NOT EXISTS info_1 LONGTEXT NULL AFTER num_cliente_phc,
  ADD COLUMN IF NOT EXISTS info_2 LONGTEXT NULL AFTER info_1,
  ADD COLUMN IF NOT EXISTS reservado1 VARCHAR(255) NULL AFTER extras,
  ADD COLUMN IF NOT EXISTS reservado2 VARCHAR(255) NULL AFTER reservado1;
CREATE INDEX IF NOT EXISTS ix_clients_nome_simplex ON clients (nome_simplex);

